exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {
          name: 'Anna Peralta',
          email: 'anna.peralta@galvanize.com',
          company: 'Example Corporation',
          website: 'example.com',
          phone: '',
          role: 'admin',
          is_approved: true
        },
        { name: 'Valeria Filipovic',
          email: 'valeriafilipovic@gmail.com',
          company: 'Openlane',
          website: 'openlanelabs.com',
          phone: '',
          role: 'business',
          is_approved: true },
        { name: 'Henricus Pearson ',
          email: 'henricuspearson@gmail.com',
          company: 'Yearin',
          website: 'www.yearin.com',
          phone: '314-571-0112',
          role: 'business',
          is_approved: true },
        { name: 'Orville Proudfoot',
          email: 'orvilleproudfoot@gmail.com',
          company: 'Goodsilron Social Media',
          website: 'goodsilron.com',
          phone: '4802358203',
          role: 'business',
          is_approved: true },
        { name: 'Maria Mata',
          email: 'mariamata@gmail.com',
          company: 'Condax Data LLC',
          website: 'www.condaxdata.com',
          phone: '(303) 864-0838',
          role: 'business',
          is_approved: true },
        { name: 'Zofie Iniguez',
          email: 'zofieiniguez@gmail.com',
          company: 'Opentech Health Partners',
          website: 'www.opentechhealthpartners.com',
          phone: '602-312-3363',
          role: 'business',
          is_approved: true },
        { name: 'Akpan Oberti',
          email: 'akpanoberti@gmail.com',
          company: 'Golddex Technologies',
          website: 'http://golddex.com',
          phone: '602-359-8495',
          role: 'business',
          is_approved: true },
        { name: 'Cristiano Hale',
          email: 'cristianohale@gmail.com',
          company: 'Gogozoom Corporation',
          website: 'www.gogozoom.com',
          phone: '480.868.2610 x105',
          role: 'business',
          is_approved: true },
        { name: 'Raj Fabel',
          email: 'rajfabel@gmail.com',
          company: 'Warephase',
          website: 'Warephase.com',
          phone: '480-455-0370',
          role: 'business',
          is_approved: true },
        { name: 'Kaniehtiio Bartalotti',
          email: 'kaniehtiiobartalotti@gmail.com',
          company: 'Treequote LLC',
          website: 'www.treequote.org',
          phone: '602-688-7971',
          role: 'business',
          is_approved: true },
        { name: 'Amarjeet Pospisil',
          email: 'amarjeetpospisil@gmail.com',
          company: 'Comshift',
          website: 'www.comshift.com',
          phone: '483-243-2597',
          role: 'business',
          is_approved: true },
        { name: 'Hrodland Weimann',
          email: 'hrodlandweimann@gmail.com',
          company: 'Codehow',
          website: 'www.codehow.com',
          phone: '623-457-1812',
          role: 'business',
          is_approved: true },
        { name: 'Brijesh Sarkozi',
          email: 'brijeshsarkozi@gmail.com',
          company: 'Bioplex',
          website: 'www.bioplex.com',
          phone: '9789855428',
          role: 'business',
          is_approved: true },
        { name: 'Gillis Espenson',
          email: 'gillisespenson@gmail.com',
          company: 'Greenplus Technologies Corp',
          website: 'www.greenplus.com',
          phone: '6023789556',
          role: 'business',
          is_approved: true },
        { name: 'Dr. Chidiebube Asselman',
          email: 'chidiebubeasselman@gmail.com',
          company: 'Scotfind Health',
          website: 'www.scotfindhealth.com',
          phone: '480-996-3979',
          role: 'business',
          is_approved: true },
        { name: 'Ava Salmon',
          email: 'avasalmon@gmail.com',
          company: 'Betatech Inc.',
          website: 'https://betatech.com',
          phone: '707-787-3677',
          role: 'business',
          is_approved: true },
        { name: 'Reka Lukic',
          email: 'rekalukic@gmail.com',
          company: 'MathTouch',
          website: 'www.mathtouch.com',
          phone: '2088258591',
          role: 'business',
          is_approved: true },
        { name: 'Marcius Willis',
          email: 'marciuswillis@gmail.com',
          company: 'Inity',
          website: 'inity.com',
          phone: '3148881296',
          role: 'business',
          is_approved: true },
        { name: 'Manoj Hummel',
          email: 'manojhummel@gmail.com',
          company: 'Ontomedia',
          website: 'Ontomedia.org',
          phone: '623-951-0889',
          role: 'business',
          is_approved: true },
        { name: 'Olga Blecher',
          email: 'olgabletcher@gmail.com',
          company: 'Konmatfix Academy',
          website: 'www.konmatfixacademy.com',
          phone: '603-862-4771',
          role: 'business',
          is_approved: true },
        { name: 'Adnan Newman',
          email: 'admannewman@gmail.com',
          company: 'Stark Industries',
          website: 'www.starkindustries.com',
          phone: '602-558-2297',
          role: 'business',
          is_approved: true },
        { name: 'Kimball Appeldoorn',
          email: 'kimballappeldoorn@gmail.com',
          company: 'Acme Corporation',
          website: 'acme.com',
          phone: '6176108547',
          role: 'business',
          is_approved: true },
        { name: 'Kevin Adamson',
          email: 'kevinadamson@gmail.com',
          company: 'Massive Dynamic',
          website: 'massivedynamic.com',
          phone: '4808846602',
          role: 'business',
          is_approved: true },
        { name: 'Porfirio Laska',
          email: 'porfiriolaska@gmail.com',
          company: 'Galvanize - Phoenix',
          website: 'galvanize.com',
          phone: '6023405487',
          role: 'business',
          is_approved: true },
        { name: 'Irma Fertig',
          email: 'irmafertig@gmail.com',
          company: 'Sterling Training & Consulting, LLC.',
          website: 'SterlingQuest.com ',
          phone: '6238280142',
          role: 'business',
          is_approved: true },
        { name: 'Gunne Quirk',
          email: 'gunnequirk@gmail.com',
          company: 'Umbrella Enterprises',
          website: 'umbrellaenterprises.com',
          phone: '4862453593',
          role: 'business',
          is_approved: true },
        { name: 'Fletcher Harman',
          email: 'fletcherharman@gmail.com',
          company: 'Center for Special Needs',
          website: 'http://centerforspecialneeds.com/',
          phone: '4807769179',
          role: 'business',
          is_approved: true },
        { name: 'Angharad Ryskamp',
          email: 'angharadryskamp@gmail.com',
          company: 'Phoenix Creative',
          website: 'www.phxcreative.com',
          phone: '9703134357',
          role: 'business',
          is_approved: true },
        { name: 'Giovanna Matsumoto',
          email: 'giovannamatsumoto@gmail.com',
          company: null,
          website: null,
          phone: null,
          role: 'student',
          is_approved: true },
        { name: 'Daniel Souza',
          email: 'danielsouza@gmail.com',
          company: null,
          website: null,
          phone: null,
          role: 'student',
          is_approved: true },
        { name: 'Gertruda Minett',
          email: 'gertrudaminett@gmail.com',
          company: null,
          website: null,
          phone: null,
          role: 'student',
          is_approved: true },
        { name: 'John Doe',
          email: 'johndoe@gmail.com',
          company: null,
          website: null,
          phone: null,
          role: 'student',
          is_approved: false },
        { name: 'Jane Doe',
          email: 'janedoe@gmail.com',
          company: null,
          website: null,
          phone: null,
          role: 'student',
          is_approved: false }
      ]);
    });
};
